# Terraform backend configuration for staging environment
# Auto-generated by setup-remote-state.sh
bucket         = "terraform-state-950224716055-staging"
key            = "static-site-deploy/staging/terraform.tfstate"
region         = "us-east-1"
dynamodb_table = "terraform-state-lock-staging"
encrypt        = true
